apiVersion: v2
name: trino-history-server
description: Helm chart for deploying the Trino History Server backend and a custom Web UI.
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: trino
    alias: webui
    version: 1.39.1
    repository: https://trinodb.github.io/charts
    condition: webui.enabled
