{{- $scheme := ternary "https" "http" .Values.server.https.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-service-configuration
  labels:
    {{- include "trino-history-server.labels" . | nindent 4 }}
data:
  BACKEND_SERVICE_URL: {{ $scheme }}://{{ include "trino-history-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}
  BACKEND_QUERY_PATH: {{ .Values.server.queryPath }}
