{{- $storageType := index .Values.server.properties "storage.type" | default "filesystem" }}
{{- if eq $storageType "filesystem" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trino-history-server.fullname" . }}-data
  labels:
    {{- include "trino-history-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.fileSystemPvcSize | default "1Gi" }}
{{- end }}
