apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino-history-server.fullname" . }}-properties
  labels:
    {{- include "trino-history-server.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.server.properties }}
  {{ $key | replace "." "_" | replace "-" "" | upper }}: {{ $value | quote}}
  {{- end }}